### PR TITLE
Sync back with horde upstream

### PR DESCRIPTION
**Pull request by ralflang**
Not sure if there is really anything that needs syncing.

### CODE REVIEW

**Comment by ralflang** [comment]
5 commits but no changes.
@midahp I suppose it's better to simply force push upstream over maintaina-com/FRAMEWORK_6_0 to address this pseudo difference. Please close this PR after checking / performing.

**Comment by midahp** [comment]
done. The only difference was the version in Application.php. That was still `H5 (5.0.0alpha7)` in maintaina-com/FRAMEWORK_6_0. Now it is also `H6 (5.0.0alpha7)`.

(not sure how much sense it makes to have H6 still be version 5.x.x but that is another issue)

**Comment by midahp** [comment]
@ralflang I have no permission to close this PR

**Comment by ralflang** [comment]
Closing as per your request

**Pull request closed without merging**
